-- MySQL Script generated by MySQL Workbench
-- Mon Nov 14 18:08:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Variété de cookie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Variété de cookie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Variété de cookie` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Size` INT NULL,
  `price` INT NULL,
  `Introduction_date` DATE NOT NULL,
  `Stop date` DATE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ingredients` (
  `ID` INT NOT NULL,
  `Description` VARCHAR(255) NULL,
  `ID_provider` INT NULL,
  `catalogue_ID` INT NULL,
  `Price` INT NULL,
  `Introduction_Date` DATE NULL,
  `Stopping_Date` DATE NULL,
  `Supply_delay_in_days` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table3` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table3` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table4`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table4` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table4` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
